pipeline:
  name: testing-git exp
  identifier: testinggit_exp
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: testignorecase
        repoName: test-ignore-case
        build: <+input>
  stages:
    - stage:
        name: ci test
        identifier: ci_test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_connector
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Plugin
                  name: Plugin_1
                  identifier: Plugin_1
                  spec:
                    connectorRef: DockerTestk8
                    image: plugins/slack
